name: pharaoh_shell
description: Custom Flutter Wayland shell for Pharaoh OS.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  dbus: ^0.7.8
  intl: ^0.18.1
  collection: ^1.17.2
  system_tray: ^2.0.3
  window_manager: ^0.3.5
  yaml: ^3.1.2
  file: ^6.1.4
  url_launcher: ^6.2.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/wallpapers/
