name: pharaohsearch
description: Privacy-first browser for Pharaoh OS.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  webview_flutter: ^4.4.2
  webview_flutter_linux: ^0.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/filters/easylist.txt
