name: Build Pharaoh OS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential debootstrap grub-pc-bin grub-efi-amd64-bin \
            xorriso mtools squashfs-tools qemu-system-x86 nasm curl git \
            flatpak apparmor apparmor-utils nftables clang cmake ninja-build \
            pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Flutter desktop
        run: |
          flutter config --enable-linux-desktop
          flutter --version

      - name: Build rootfs & shell
        run: |
          make deps
          make rootfs
          make overlay
          make shell
          make iso-bios

      - name: Upload BIOS ISO
        uses: actions/upload-artifact@v4
        with:
          name: PharaohOS-bios.iso
          path: out/PharaohOS-bios.iso
          if-no-files-found: error
